import os
from dataclasses import dataclass, field
from typing import List
import time
import adalflow as adal
from dotenv import load_dotenv


# ---------------------------------------------------------
# Load environment variables
# ---------------------------------------------------------
load_dotenv()


# ---------------------------------------------------------
# Structured output schema
# ---------------------------------------------------------
@dataclass
class AnalysisReport(adal.DataClass):
    """
    Structured output generated by the AdalFlow Report Agent.
    """

    answer: str = field(
        metadata={
            "desc": "A direct and concise answer to the user's question."
        }
    )

    recommendation: str = field(
        metadata={
            "desc": "Concrete recommendations based only on the analysis findings."
        }
    )

    key_findings: List[str] = field(
        metadata={
            "desc": "Important findings extracted from the analysis."
        }
    )

    __output_fields__ = [
        "answer",
        "recommendation",
        "key_findings",
    ]


# ---------------------------------------------------------
# Prompt template
# ---------------------------------------------------------
REPORT_TEMPLATE = r"""
<START_OF_SYSTEM_MESSAGE>

You are the Report Agent of an autonomous data-analysis system.

Your task is to generate a concise analytical report using ONLY
the information provided in the analysis findings.

Rules:

1. Do not invent numbers, predictions, methods, or claims.
2. Use only the information provided in the input.
3. Do not introduce information from your own knowledge.
4. If a specific individual prediction was not computed,
   clearly state that an individual prediction was not computed.
5. Keep the answer concise and practical.
6. Extract important findings from the supplied analysis.
7. Return the answer in exactly the required structured format.

{{ output_format_str }}

<END_OF_SYSTEM_MESSAGE>


<START_OF_USER_MESSAGE>

USER QUESTION:
{{ question }}


DATA FINDINGS:
{{ data_findings }}


FEATURE IMPORTANCE:
{{ feature_importance }}


RESEARCH FINDINGS:
{{ research_findings }}


PREDICTION RESULT:
{{ prediction_result }}

<END_OF_USER_MESSAGE>
"""


# ---------------------------------------------------------
# AdalFlow Report Generator
# ---------------------------------------------------------
class AdalFlowReportGenerator(adal.Component):

    def __init__(self):
        super().__init__()

        # ---------------------------------------------
        # Structured output parser
        # ---------------------------------------------
        self.parser = adal.DataClassParser(
            data_class=AnalysisReport,
            return_data_class=True,
        )

        # ---------------------------------------------
        # Groq LLM
        # ---------------------------------------------
        self.generator = adal.Generator(
            model_client=adal.GroqAPIClient(),
            model_kwargs={
                "model": "openai/gpt-oss-20b",
                "temperature": 0,
            },
            template=REPORT_TEMPLATE,
            prompt_kwargs={
                "output_format_str": self.parser.get_output_format_str(),
            },
            output_processors=self.parser,
        )

    # ---------------------------------------------
    # Main component
    # ---------------------------------------------
    def call(
        self,
        question: str,
        data_findings: str,
        feature_importance: str,
        research_findings: str,
        prediction_result: str,
    ):
        start_time = time.time()

        response = self.generator(
            prompt_kwargs={
                "question": question,
                "data_findings": data_findings,
                "feature_importance": feature_importance,
                "research_findings": research_findings,
                "prediction_result": prediction_result,
            }
        )

        elapsed_time = time.time() - start_time

        print(f"AdalFlow Report Generation Time: {elapsed_time:.2f}s")

        if response.data is not None:
            print("Structured output parsing: SUCCESS")
        else:
            print("Structured output parsing: FAILED")

        return response

    def generate_from_state(self, state):
        """
        Generate an AdalFlow report from the existing AutoAnalyst AgentState.
        """

        feature_importance = state.get("feature_importance", [])

        if feature_importance:
            feature_importance_text = "\n".join(
                f"{name}: {float(value):.3f}"
                for name, value in feature_importance[:5]
            )
        else:
            feature_importance_text = (
                "No feature importance data is available."
            )

        critique = state.get("critique", "")

        if critique:
            research_findings = (
                f"{state.get('research_findings', 'No research findings available.')}"
                f"\n\nCRITIC FEEDBACK:\n{critique}"
            )
        else:
            research_findings = state.get(
                "research_findings",
                "No research findings available."
            )

        return self(
            question=state.get(
                "question",
                "Analyze this dataset and summarize the key findings."
            ),
            data_findings=state.get(
                "data_findings",
                "No data findings available."
            ),
            feature_importance=feature_importance_text,
            research_findings=research_findings,
            prediction_result=state.get(
                "prediction_result",
                "Not computed in this analysis."
            ),
        )